### PR TITLE
将README.md翻译成简体中文

### PR DESCRIPTION
**Pull request by ChaosJohn**

### CODE REVIEW

**Comment by explora26** [comment]
Hi @ChaosJohn ,

Why would you want to send this pull request?

**Comment by johannjhang** [comment]
翻成 README.cn.md 的話相信作者會收。只是取代的話就變成敏感議題了。

**Comment by ChaosJohn** [comment]
Sorry, it's my first time to do such work, I just want to make a cn-copy instead of replacing it. I'll be more careful later.

**Comment by yongjhih** [comment]
It's ok, thanks for your gantleness.

**Pull request merged**
